# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reddit_post_pb2 as reddit__post__pb2


class RedditReaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRedditPost = channel.unary_unary(
                '/reddit_post.RedditReader/GetRedditPost',
                request_serializer=reddit__post__pb2.RedditPostRequest.SerializeToString,
                response_deserializer=reddit__post__pb2.RedditPostResponse.FromString,
                )


class RedditReaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRedditPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedditReaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRedditPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRedditPost,
                    request_deserializer=reddit__post__pb2.RedditPostRequest.FromString,
                    response_serializer=reddit__post__pb2.RedditPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reddit_post.RedditReader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RedditReader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRedditPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reddit_post.RedditReader/GetRedditPost',
            reddit__post__pb2.RedditPostRequest.SerializeToString,
            reddit__post__pb2.RedditPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
