# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit_post.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11reddit_post.proto\x12\x0breddit_post\"Y\n\x11RedditPostRequest\x12\x15\n\x08post_url\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07post_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_post_urlB\n\n\x08_post_id\"1\n\x12RedditPostResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t2b\n\x0cRedditReader\x12R\n\rGetRedditPost\x12\x1e.reddit_post.RedditPostRequest\x1a\x1f.reddit_post.RedditPostResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reddit_post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDDITPOSTREQUEST']._serialized_start=34
  _globals['_REDDITPOSTREQUEST']._serialized_end=123
  _globals['_REDDITPOSTRESPONSE']._serialized_start=125
  _globals['_REDDITPOSTRESPONSE']._serialized_end=174
  _globals['_REDDITREADER']._serialized_start=176
  _globals['_REDDITREADER']._serialized_end=274
# @@protoc_insertion_point(module_scope)
